create database student;
use student;
create table details(rollno varchar(100),name char(19),dept char(188));
insert into details values('1','jothi','ece');
show databases;
select * from details;
drop table details;
show  databases;
show tables;
create database production;
use production;
create table product(empname char(100),productname char(100));
insert into product values('jothi','phone');
show databases;
alter table product add sales varchar(100);
insert into product values('jothi','phone','1000');
select * from  product;
create database employee;
use employee;
create table empdetails(empno varchar(100),employeename char(199));
insert into empdetails values('12','sri');
select * from empdetails;
